// automatically generated by the FlatBuffers compiler, do not modify

package com.newrelic.mobile.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DoubleSessionAttribute extends Table {
  public static DoubleSessionAttribute getRootAsDoubleSessionAttribute(ByteBuffer _bb) { return getRootAsDoubleSessionAttribute(_bb, new DoubleSessionAttribute()); }
  public static DoubleSessionAttribute getRootAsDoubleSessionAttribute(ByteBuffer _bb, DoubleSessionAttribute obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public DoubleSessionAttribute __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public double value() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public boolean mutateValue(double value) { int o = __offset(6); if (o != 0) { bb.putDouble(o + bb_pos, value); return true; } else { return false; } }

  public static int createDoubleSessionAttribute(FlatBufferBuilder builder,
      int nameOffset,
      double value) {
    builder.startObject(2);
    DoubleSessionAttribute.addValue(builder, value);
    DoubleSessionAttribute.addName(builder, nameOffset);
    return DoubleSessionAttribute.endDoubleSessionAttribute(builder);
  }

  public static void startDoubleSessionAttribute(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(1, value, 0.0); }
  public static int endDoubleSessionAttribute(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // name
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) { return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb); }

  public static DoubleSessionAttribute __lookup_by_key(DoubleSessionAttribute obj, int vectorLocation, String key, ByteBuffer bb) {
    byte[] byteKey = key.getBytes(Table.UTF8_CHARSET.get());
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = compareStrings(__offset(4, bb.capacity() - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return (obj == null ? new DoubleSessionAttribute() : obj).__assign(tableOffset, bb);
      }
    }
    return null;
  }
}

