// automatically generated by the FlatBuffers compiler, do not modify

package com.newrelic.mobile.fbs;

public final class Framework {
  private Framework() { }
  public static final byte Native = 0;
  public static final byte ReactNative = 1;

  public static final String[] names = { "Native", "ReactNative", };

  public static String name(int e) { return names[e]; }
}

