// automatically generated by the FlatBuffers compiler, do not modify

package com.newrelic.mobile.fbs;

public final class Platform {
  private Platform() { }
  public static final byte Android = 0;
  public static final byte iOS = 1;
  public static final byte tvOS = 2;

  public static final String[] names = { "Android", "iOS", "tvOS", };

  public static String name(int e) { return names[e]; }
}

