// automatically generated by the FlatBuffers compiler, do not modify

package com.newrelic.mobile.fbs.ios;

public final class Arch {
  private Arch() { }
  public static final byte armv7 = 0;
  public static final byte arm64 = 1;

  public static final String[] names = { "armv7", "arm64", };

  public static String name(int e) { return names[e]; }
}

