// automatically generated by the FlatBuffers compiler, do not modify

package com.newrelic.mobile.fbs.models;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InteractionTrace extends Table {
  public static InteractionTrace getRootAsInteractionTrace(ByteBuffer _bb) { return getRootAsInteractionTrace(_bb, new InteractionTrace()); }
  public static InteractionTrace getRootAsInteractionTrace(ByteBuffer _bb, InteractionTrace obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public InteractionTrace __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long start() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateStart(long start) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, start); return true; } else { return false; } }
  public long end() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateEnd(long end) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, end); return true; } else { return false; } }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public float duration() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateDuration(float duration) { int o = __offset(10); if (o != 0) { bb.putFloat(o + bb_pos, duration); return true; } else { return false; } }
  public String protocolVersion() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer protocolVersionAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer protocolVersionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String content() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createInteractionTrace(FlatBufferBuilder builder,
      long start,
      long end,
      int nameOffset,
      float duration,
      int protocolVersionOffset,
      int contentOffset) {
    builder.startObject(6);
    InteractionTrace.addEnd(builder, end);
    InteractionTrace.addStart(builder, start);
    InteractionTrace.addContent(builder, contentOffset);
    InteractionTrace.addProtocolVersion(builder, protocolVersionOffset);
    InteractionTrace.addDuration(builder, duration);
    InteractionTrace.addName(builder, nameOffset);
    return InteractionTrace.endInteractionTrace(builder);
  }

  public static void startInteractionTrace(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addStart(FlatBufferBuilder builder, long start) { builder.addLong(0, start, 0L); }
  public static void addEnd(FlatBufferBuilder builder, long end) { builder.addLong(1, end, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static void addDuration(FlatBufferBuilder builder, float duration) { builder.addFloat(3, duration, 0.0f); }
  public static void addProtocolVersion(FlatBufferBuilder builder, int protocolVersionOffset) { builder.addOffset(4, protocolVersionOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(5, contentOffset, 0); }
  public static int endInteractionTrace(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

