name: Android CI

on:
  push:
    branches: [ "develop", "main", "feature/*" ]
  pull_request:
    branches: [ "develop", "main" ]

  workflow_dispatch:
    inputs:
    #  working-branch:
    #    description: 'TBA: Build this branch (default is current)'
    #    required: false
    #    default: ${{ env.GITHUB_REF_NAME }}
    #    type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: current
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build-step
        run: ./gradlew build
      - name: Upload build reports
        if: failure() && steps.build-step.outcome != 'success'
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
            agent/build/reports/tests/test/
            agent-core/build/reports/tests/test/
            instrumentation/gradle/build/reports/tests/test/
            plugins/gradle/build/reports/tests/test
          if-no-files-found: ignore
          retention-days: 7
