name: Android CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  validateAGP8:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agp: [ '8.0.0','8.0.1','8.0.2','8.1.0']

    name: AGP Matrix Release - AGP ${{ matrix.agp }} - Integrations ${{ matrix.integrations }}
    env:
      VERSION_AGP: ${{ matrix.agp }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'     

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
         ./gradlew wrapper --gradle-version=8.0
         ./gradlew sync
         ./gradlew build