name: Android CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: current
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build-step
        run: ./gradlew build
      - name: Upload build reports
        if: failure() && steps.build-step.outcome != 'success'
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
            agent/build/reports/tests/test/
            agent-core/build/reports/tests/test/
            instrumentation/gradle/build/reports/tests/test/
            plugins/gradle/build/reports/tests/test
            if-no-files-found: ignore
            retention-days: 15

  validateAGP7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agp: ['7.1.0','7.1.1','7.1.2','7.1.3','7.2.0','7.2.1','7.2.2','7.3.0','7.3.1','7.4.0','7.4.1','7.4.2']
        
    name: AGP Matrix Release - AGP ${{ matrix.agp }} - Integrations ${{ matrix.integrations }}
    env:
      VERSION_AGP: ${{ matrix.agp }}

    steps:
    - uses: actions/checkout@v3
    - name: Validate with JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
         ./gradlew wrapper --gradle-version=7.2
         ./gradlew sync
         ./gradlew build
    - name: Validate with JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
        ./gradlew wrapper --gradle-version=7.2
        ./gradlew sync
        ./gradlew build
    - name: Validate with JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
           ./gradlew wrapper --gradle-version=7.2
           ./gradlew sync
           ./gradlew build