name: Android CI with AGP8

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  validateAGP8:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agp: [ '8.0.0','8.0.1','8.0.2','8.1.0']

    name: AGP Matrix Test - AGP ${{ matrix.agp }}
    env:
      VERSION_AGP: ${{ matrix.agp }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        check-latest: true
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Stage with Gradle
      run: ./gradlew install publish
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
