name: Android Assemble

on:
  workflow_dispatch:
  push:
    branches: [ develop, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ develop, main, feature/** ]

jobs:
  cache-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install cache
        id: cache_setup
        uses: actions/cache@v3
        with:
          path: |
            /root/.android
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - run: env | sort

  sdk-setup:
    runs-on: ubuntu-latest
    needs: [ cache-setup ]
    steps:
      - name: Set up JDK 11
        id: jdk_setup
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK/NDK
        id: sdk_ndk_setup
        uses: amyu/setup-android@v1.1
        with:
          is-use-cache: false
          ## values taken from https://github.com/newrelic/android-agent-ndk/blob/develop/buildconfig.gradle#L46-L50
          sdk-version: '28'
          build-tools-version: '30.0.3'
          cmake-version: '3.18.1'
          ndk-version: '21.4.7075529'
      - run: env | sort

  build-setup:
    runs-on: ubuntu-latest
    needs: [ cache-setup ]
    steps:
      - uses: actions/checkout@v3
        id: source_setup

      - uses: amadornes/parse-properties-action@v1.0
        id: parse_properties
        with:
          file: 'gradle.properties'

      - name: Increment Build Number
        uses: travisj/build-number-action@v1.0.2
        id: build_number

      - name: Update build property
        uses: dschanoeh/change-property@v1
        with:
          file: gradle.properties
          property: newrelic.version.build
          value: ${{ steps.build_number.outputs.build-number }}

      - name: Properties
        run: |
          echo "newrelic.version [${{ steps.parse_properties.outputs.newrelic.version }}]"
          echo "newrelic.agent.version [${{ steps.parse_properties.outputs.newrelic.agent.version }}]"
          echo "newrelic.agent.version.build [${{ steps.build_number.outputs.build-number }}]"

      - name: Build Info
        run: echo "AGENT VERSION[$AGENT_VERSION] BUILD_NUMBER[$BUILD_NUMBER]"
        env:
          AGENT_VERSION: ${{ steps.parse_properties.outputs.agent.version }}
          BUILD_NUMBER: ${{ steps.build_number.outputs.build-number }}
      - run: cat gradle.properties

  assemble:
    runs-on: ubuntu-latest
    needs: [ cache-setup ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          # gpg-private-key: ${{ secrets.SIGNING_GPG_KEY }}
          gpg-passphrase: ${{ secrets.SIGNING_PASSPHRASE }}

      - name: Setup Android SDK/NDK
        id: sdk_ndk_setup
        uses: amyu/setup-android@v1.1
        with:
          is-use-cache: false
          ## values taken from https://github.com/newrelic/android-agent-ndk/blob/develop/buildconfig.gradle#L46-L50
          sdk-version: '28'
          build-tools-version: '30.0.3'
          cmake-version: '3.18.1'
          ndk-version: '21.4.7075529'

      - run: |
          echo "pwd[`pwd`]"
          ls -aFl
          env | sort
          ls -aFl /root

      - run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew assembleD -Pnewrelic.version.build=${{ env.GITHUB_RUN_ID }} --stacktrace

