name: Generate Codecov Report

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  codecov_report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
          
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Run jacoco
      run: |
        ./gradlew agent:testReleaseUnitTestCoverage
        ./gradlew agent-core:jacocoTestReport
        ./gradlew instrumentation:jacocoTestReport
        ./gradlew plugin:gradle:jacocoTestReport

    - name: Upload Test Report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: |
          ./agent/build/reports/jacoco/testReleaseUnitTestCoverage/testReleaseUnitTestCoverage.xml,
          ./agent-core/build/reports/jacoco/test/jacocoTestReport.xml,
          ./instrumentation/build/reports/jacoco/test/jacocoTestReport.xml,
          ./plugins/gradle/build/reports/jacoco/test/jacocoTestReport.xml
