name: Gradle Plugin Portal Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "release" ]
    types:
      - completed

jobs:
  assemble_project:
    name: Assemble project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew clean assemble --no-daemon

  publish_release:
      name: Publish artifacts
      needs: [assemble_project]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'gradle'
        - name: Publish to Gradle Plugin Portal
          env:
            ORG_GRADLE_PROJECT_gradlePublishKey : ${{ secrets.GRADLE_PUBLISH_KEY  }}
            ORG_GRADLE_PROJECT_gradlePublishSecret: ${{ secrets.GRADLE_PUBLISH_SECRET  }}
          run: ./gradlew clean plugins:gradle:publishPlugins --max-workers 1


