name: Add JIRA Links
on:
  pull_request:
    types: [opened, edited, reopened]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  add-jira-links:
    runs-on: ubuntu-latest
    steps:
      - uses: codenamegrant/jira-pr-link-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-base-url: 'https://newrelic.atlassian.net'
          jira-link-mode: 'body-start'
          issue-pattern: '(NR-\d+)'
