name: notify-subscribers

on:
  release:
    types: ['published']

permissions:
  contents: read

jobs:
  notify:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Channel
        id: notify
        env:
          RELEASE_URL: ${{ github.event.release.html_url }}
          SLACK_WEBHOOK_TOKEN: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"The Android mobile agent has created a new release candidate ${RELEASE_URL}\"}" \
            "https://hooks.slack.com/services/${SLACK_WEBHOOK_TOKEN}"
