name: release-please

on:
  push:
    branches:
      - develop

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4 -- using sha to avoid malicious changes
        with:
          fetch-depth: 0

      - id: release-token
        env:
          RELEASE_BOT_PAT: ${{ secrets.RELEASE_BOT_PAT }}
          RELEASE_PLEASE_DEFAULT_TOKEN: ${{ github.token }}
        run: |
          if [ -n "$RELEASE_BOT_PAT" ]; then
            echo "::add-mask::$RELEASE_BOT_PAT"
            echo "token=$RELEASE_BOT_PAT" >> "$GITHUB_OUTPUT"
          else
            echo "::add-mask::$RELEASE_PLEASE_DEFAULT_TOKEN"
            echo "token=$RELEASE_PLEASE_DEFAULT_TOKEN" >> "$GITHUB_OUTPUT"
          fi

      - id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 #v5 -- using sha to avoid malicious changes
        with:
          token: ${{ steps.release-token.outputs.token }}
          target-branch: develop
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
