name: update-main

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to fast-forward to
        required: true

permissions:
  contents: write

jobs:
  update-main:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4 -- using sha to avoid malicious changes
        with:
          ref: main
          token: ${{ secrets.RELEASE_BOT_PAT }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fast-forward main
        env:
          TAG: ${{ github.event.release.tag_name || inputs.tag }}
        run: |
          git fetch origin --tags --force
          git merge --ff "$TAG"
          git push origin main
